### ISSUE TITLE
使用 go mod 默认情况下无法拉到 v2 版本

### ISSUE THREAD

**Issue by aggresss** [qiniu/http#1]
参考：
  https://studygolang.com/articles/25148?fr=sidebar

当前最新版本是 v2.0.2，但如果 go.mod 文件不做声明的化，只能拉到 v1.0.2 版本

**Comment by xushiwei** [comment]
这是因为 go mod 只支持 v0.x 或 v1.x。这个我们改改。

**Comment by xushiwei** [comment]
https://github.com/qiniu/http/releases/tag/v1.2.3
修改了版本规则，将 v2.x 改为 v1.2.x 版本。
